# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/TWI_MetaMask_Integeration/WebAssembly

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/TWI_MetaMask_Integeration/WebAssembly

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/TWI_MetaMask_Integeration/WebAssembly/CMakeFiles /mnt/d/TWI_MetaMask_Integeration/WebAssembly/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/TWI_MetaMask_Integeration/WebAssembly/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crypto_guard_if

# Build rule for target.
crypto_guard_if: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto_guard_if
.PHONY : crypto_guard_if

# fast build rule for target.
crypto_guard_if/fast:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/build
.PHONY : crypto_guard_if/fast

crypto_guard_if.o: crypto_guard_if.c.o

.PHONY : crypto_guard_if.o

# target to build an object file
crypto_guard_if.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/crypto_guard_if.c.o
.PHONY : crypto_guard_if.c.o

crypto_guard_if.i: crypto_guard_if.c.i

.PHONY : crypto_guard_if.i

# target to preprocess a source file
crypto_guard_if.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/crypto_guard_if.c.i
.PHONY : crypto_guard_if.c.i

crypto_guard_if.s: crypto_guard_if.c.s

.PHONY : crypto_guard_if.s

# target to generate assembly for a file
crypto_guard_if.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/crypto_guard_if.c.s
.PHONY : crypto_guard_if.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.c.s

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.o: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.o

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.o

# target to build an object file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.o:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.o
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.o

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.i: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.i

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.i

# target to preprocess a source file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.i:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.i
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.i

mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.s: mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.s

.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.s

# target to generate assembly for a file
mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.s:
	$(MAKE) -f CMakeFiles/crypto_guard_if.dir/build.make CMakeFiles/crypto_guard_if.dir/mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.s
.PHONY : mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... crypto_guard_if"
	@echo "... crypto_guard_if.o"
	@echo "... crypto_guard_if.i"
	@echo "... crypto_guard_if.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/WalletCoreInterface/USBWallet/twi_usb_wallet_if.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/crc_16.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_common.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/helpers/source/twi_debug.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_link_layer.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_network_layer.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_no_security_layer.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_stack.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/protocols/twi_generic_stack_proto/src/twi_usb_link_layer.s"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.o"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.i"
	@echo "... mnt/d/TWI_MetaMask_Integeration/TWIWalletCore/utils/twi_apdu_parser_composer/twi_apdu_parser_composer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

